### ISSUE TITLE
pulumi up fails with. function undefined

### ISSUE THREAD

**Issue by leanderc2018** [pulumi/apps#3]
Pulumi up fails with function undefined

Diagnostics:
 pulumi:pulumi:Stack (eks-cluster-testing):
                                 ^
   SyntaxError: FunctionGetScript is not defined
       at new Function (<anonymous>)
       at Object.<anonymous> (/Users/cloudcover/Documents/cc_git_repo/scripts/pulumi_eks/node_modules/@pulumi/pulumi/runtime/closure/v8.js:33:1)
       at Module._compile (internal/modules/cjs/loader.js:759:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
       at Module.load (internal/modules/cjs/loader.js:628:32)
       at Function.Module._load (internal/modules/cjs/loader.js:555:12)
       at Module.require (internal/modules/cjs/loader.js:666:19)
       at require (internal/modules/cjs/helpers.js:16:16)
       at Object.<anonymous> (/Users/cloudcover/Documents/cc_git_repo/scripts/pulumi_eks/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:32:12)
       at Module._compile (internal/modules/cjs/loader.js:759:30)

   error: an unhandled error occurred: Program exited with non-zero exit code: 1

Also Found incompatible version issues of pulumi, but corrected it by editing the versions in the .json as appropriate.

**Comment by lukehoban** [comment]
Which version of Node are you using?

```
$ node -v
v8.11.1
```

**Comment by ericrudder** [comment]
by chance, did you base your JS program on a TypeScript example?

**Comment by leanderc2018** [comment]
> Which version of Node are you using?
> 
> ```
> $ node -v
> v8.11.1
> ```

node -v
v12.1.0

**Comment by lukehoban** [comment]
cc @ellismg @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
odd.   FunctionGetScript is in our v10andLower.ts file  (for use on node v10 and below).

v12 should be pulling in v11andHigher.ts and should not use FunctionGetScript...

I would expect this to be failing in CI since we test v12 there...

**Comment by CyrusNajmabadi** [comment]
> at Object. (/Users/cloudcover/Documents/cc_git_repo/scripts/pulumi_eks/node_modules/@pulumi/pulumi/runtime/closure/v8.js:33:1)

this is highly suspect.  It's probable that this is an ancient version of pulumi/pulumi since tha'ts not a valid line in our current versions.  @leanderc2018 What versions of your `@pulumi/...` modules are you using?  It's quite possible that an older version was not node v12 compatible.

**Comment by lukehoban** [comment]
> ancient version of pulumi/pulumi

That would make sense.  This is probably related to https://github.com/pulumi/apps/blob/master/eks/package.json being pinned to some old versions which should likely be `latest` instead.

**Comment by leanderc2018** [comment]
Do you guys mean this?
NAME        KIND      VERSION  SIZE    INSTALLED     LAST USED
aws         resource  0.18.3   195 MB  1 week ago    now
aws         resource  0.15.1   143 MB  14 hours ago  now
gcp         resource  0.18.5   75 MB   1 week ago    now
kubernetes  resource  0.17.5   48 MB   14 hours ago  now
vsphere     resource  0.17.2   60 MB   1 week ago    now

**Comment by leanderc2018** [comment]
pulumi version
v0.17.12

**Comment by leanderc2018** [comment]
Issue still persists :(

**Comment by lukehoban** [comment]
This should be fixed with https://github.com/pulumi/apps/commit/6b47e0d85d8f69728d9f7b1e4e6e54b40bdf43c0.
